# Generated by Django 2.2 on 2021-10-26 12:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Глобальный идентификатор')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование справочника')),
                ('short_name', models.CharField(max_length=50, verbose_name='Короткое наименование')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('version', models.CharField(db_index=True, max_length=200, verbose_name='Версия')),
                ('date_commencement', models.DateField(blank=True, null=True, verbose_name='Дата начала действия справочника')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия справочника')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='UnitManual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Глобальный идентификатор')),
                ('code_unit', models.CharField(max_length=200, verbose_name='Код элемента')),
                ('value_unit', models.CharField(max_length=200, verbose_name='Значение элемента')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.Manual')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AddConstraint(
            model_name='manual',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_Version'),
        ),
        migrations.AddConstraint(
            model_name='unitmanual',
            constraint=models.UniqueConstraint(fields=('manual', 'code_unit'), name='unique_Code_unit'),
        ),
    ]
