# Generated by Django 2.2 on 2021-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='commencement_date',
            field=models.DateField(verbose_name='Дата начала действия справочника'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='version',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Версия'),
        ),
    ]
