# Generated by Django 2.2 on 2021-10-26 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='date_commencement',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала действия справочника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manual',
            name='date_expiration',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания действия справочника'),
            preserve_default=False,
        ),
    ]
