# Generated by Django 2.2 on 2021-10-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211015_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
    ]
