# Generated by Django 2.2 on 2021-10-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211015_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='version',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Версия'),
        ),
        migrations.AddConstraint(
            model_name='manual',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_Version'),
        ),
    ]
