# Generated by Django 2.2 on 2021-10-17 09:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211017_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
