# Generated by Django 2.2 on 2021-10-17 09:33

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211017_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование справочника'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Короткое наименование'),
        ),
    ]
