# Generated by Django 2.2 on 2021-10-17 09:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211017_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', verbose_name='Короткое наименование'),
        ),
    ]
