# Generated by Django 2.2 on 2021-10-17 10:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211017_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Короткое наименование'),
        ),
    ]
