# Generated by Django 2.2 on 2021-10-17 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211017_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='slug',
        ),
        migrations.AddField(
            model_name='manual',
            name='short_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Короткое наименование'),
            preserve_default=False,
        ),
    ]
